// <auto-generated />
using System;
using Gimnasio.App.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Gimnasio.App.Persistencia.Migrations
{
    [DbContext(typeof(AppContext))]
    [Migration("20220827202052_dos")]
    partial class dos
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Gimnasio.App.Dominio.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int?>("ConsejoNutricionalId")
                        .HasColumnType("int");

                    b.Property<string>("Contraseña")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Direccion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Edad")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimerNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RutinaId")
                        .HasColumnType("int");

                    b.Property<int?>("SeguimientoId")
                        .HasColumnType("int");

                    b.Property<string>("SegundoApellido")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SegundoNombre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefono")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ConsejoNutricionalId");

                    b.HasIndex("RutinaId");

                    b.HasIndex("SeguimientoId");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.ConsejoNutricional", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ConsejoNutricionales");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.Dificultad", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Avanzado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Basica")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intermedia")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Dificultades");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.Rutina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Abdominal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DificultadId")
                        .HasColumnType("int");

                    b.Property<string>("GluteosPantorrila")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrenInferior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrenSuperior")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ValoracionInicialId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DificultadId");

                    b.HasIndex("ValoracionInicialId");

                    b.ToTable("Rutinas");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.Seguimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("DiaTrabajado")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("seguimientos");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.ValoracionInicial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Altura")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genero")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Peso")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ValoracionIniciales");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.Cliente", b =>
                {
                    b.HasOne("Gimnasio.App.Dominio.ConsejoNutricional", "ConsejoNutricional")
                        .WithMany()
                        .HasForeignKey("ConsejoNutricionalId");

                    b.HasOne("Gimnasio.App.Dominio.Rutina", "Rutina")
                        .WithMany()
                        .HasForeignKey("RutinaId");

                    b.HasOne("Gimnasio.App.Dominio.Seguimiento", "Seguimiento")
                        .WithMany()
                        .HasForeignKey("SeguimientoId");

                    b.Navigation("ConsejoNutricional");

                    b.Navigation("Rutina");

                    b.Navigation("Seguimiento");
                });

            modelBuilder.Entity("Gimnasio.App.Dominio.Rutina", b =>
                {
                    b.HasOne("Gimnasio.App.Dominio.Dificultad", "Dificultad")
                        .WithMany()
                        .HasForeignKey("DificultadId");

                    b.HasOne("Gimnasio.App.Dominio.ValoracionInicial", "ValoracionInicial")
                        .WithMany()
                        .HasForeignKey("ValoracionInicialId");

                    b.Navigation("Dificultad");

                    b.Navigation("ValoracionInicial");
                });
#pragma warning restore 612, 618
        }
    }
}
